# [[plugins]]
# repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <F8> :NERDTreeFind<CR>
  "nnoremap <C-w>j :<C-w>j<ESC>:NERDTreeFind<CR>
  nnoremap <silent> <F9> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = 'let g:vim_markdown_conceal = 0'

[[plugins]]
repo = 'aklt/plantuml-syntax'

# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# on_if = '!has("nvim")'

# [[plugins]]
# repo = 'roxma/nvim-yarp'
# on_if = '!has("nvim")'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'nnoremap <Leader>tb :TagbarToggle<CR>'
hook_source = '''
  " gotags setting
  let g:tagbar_type_go = {
      \ 'ctagstype' : 'go',
      \ 'kinds'     : [
          \ 'p:package',
          \ 'i:imports:1',
          \ 'c:constants',
          \ 'v:variables',
          \ 't:types',
          \ 'n:interfaces',
          \ 'w:fields',
          \ 'e:embedded',
          \ 'm:methods',
          \ 'r:constructor',
          \ 'f:functions'
      \ ],
      \ 'sro' : '.',
      \ 'kind2scope' : {
          \ 't' : 'ctype',
          \ 'n' : 'ntype'
      \ },
      \ 'scope2kind' : {
          \ 'ctype' : 't',
          \ 'ntype' : 'n'
      \ },
      \ 'ctagsbin'  : 'gotags',
      \ 'ctagsargs' : '-sort -silent'
  \ }
'''
