[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  let NERDSpaceDelims = 1
  nmap ,, <Plug>NERDCommenterToggle
  vmap ,, <Plug>NERDCommenterToggle
  " vim-vue plugin settings
  let g:ft = ''
  function! NERDCommenter_before()
    if &ft == 'vue'
      let g:ft = 'vue'
      let stack = synstack(line('.'), col('.'))
      if len(stack) > 0
        let syn = synIDattr((stack)[0], 'name')
        if len(syn) > 0
          exe 'setf ' . substitute(tolower(syn), '^vue_', '', '')
        endif
      endif
    endif
  endfunction
  function! NERDCommenter_after()
    if g:ft == 'vue'
      setf vue
      let g:ft = ''
    endif
  endfunction
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'Shougo/vimproc.vim'
hook_add = '''
	" TODO move to plugins/vimproc.rc.vim
  let g:quickrun_config = {}
  let g:quickrun_config._ = {'runner' : 'vimproc', "runner/vimproc/updatetime" : 10}

  " let g:quickrun_config['ruby.rspec'] = {'command': 'rspec', 'exec': 'bundle exec %c %o %s', 'cmdopt': '-cfd'}
  let g:quickrun_config['ruby.rspec'] = {'command': 'rspec', 'cmdopt': '-cfd'}
  let g:quickrun_config['ruby'] = {'cmdopt': '-w'}

  autocmd BufRead,BufNewFile *_test.go set filetype=go.test
  let g:quickrun_config['go.gotest'] = {'command': 'go test', 'cmdopt': '-run'}

  augroup GroupRspec
    autocmd!
    autocmd BufWinEnter,BufNewFile *_spec.rb set filetype=ruby.rspec
  augroup END

  augroup GroupGoTest
    autocmd!
    autocmd BufWinEnter,BufNewFile *_test.go set filetype=go.gotest
  augroup END

  nnoremap [quickrun] <Nop>
  nmap <Space>k [quickrun]
  nnoremap <silent> [quickrun]r :call QRunRspecCurrentLine()<CR>
  fun! QRunRspecCurrentLine()
    let line = line(".")
    " exe ":QuickRun -exec '%c %s%o' -cmdopt ':" . line . " -cfd'"
    exe ":QuickRun -exec 'bundle exec %c %s%o' -cmdopt ':" . line . " -cfd'"
  endfun
'''

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]]
repo = 'jimsei/winresizer'
hook_add = '''
let g:winresizer_enable = 1
let g:winresizer_start_key = '<C-E>'
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''
  let g:airline_theme_patch_func = 'AirlineThemePatch'
  function! AirlineThemePatch(palette)
    if g:airline_theme == 'molokai'
      for colors in values(a:palette.inactive)
        let colors[3] = 245
      endfor
    endif
  endfunction
'''

[[plugins]]
repo = 'posva/vim-vue'
